# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2312a99f6559596522abf2fcf427f0b4f6112a651374f0c5f2a964234bb237347f69e7f796135c486dd76f39c3183336c831b5abc0dfc29dbbd99e0c190c628

test:
  secret_key_base: 591576472bea558b082c8170a481383a702c159d90e846edb89ebf5912043b74389188c6c280bc547e46afd5a4eaec35e752a2cf9b68b50c33f5d3a7a1918c0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
